<a href="https://colab.research.google.com/github/Kirthiga2001/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy


In [2]:
import numpy as np


basics functions

*   np.array()-> creates a list, matrix ;
*   np.shape(name)-> gives the size of the array(no of rows, columns)
*   np.arange(start,stop,step)= for loop
*   np.linspace(start,stop,no of elements needed fromstart to stop)
*   np.logspae(start,stop,no of elements needed fromstart to stop in log scale)
*   np.zeros(no of 0s needed)
*   np.ones(no of 1s needed)
*   np.random.random(no of elements need betwwen 0 and 1)
*   np.random.randint(start,stop,range)







In [3]:
a=np.array([1,2,3,4])
print(np.shape(a))

(4,)


In [7]:
a=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(np.shape(a))

(4, 4)


In [11]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [14]:
np.linspace(10,20,12)

array([10.        , 10.90909091, 11.81818182, 12.72727273, 13.63636364,
       14.54545455, 15.45454545, 16.36363636, 17.27272727, 18.18181818,
       19.09090909, 20.        ])

In [15]:
np.logspace(10,20,3)

array([1.e+10, 1.e+15, 1.e+20])

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.ones(90)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.])

In [22]:
np.random.random(10)

array([0.58613125, 0.52370295, 0.04015734, 0.24912023, 0.41027577,
       0.22688767, 0.5793587 , 0.80073271, 0.99027589, 0.3321761 ])

Operations
* 

In [21]:
a=np.arange(10,20,1)
b=np.arange(20,40,2)
print(2*b)
print(a*b)

[40 44 48 52 56 60 64 68 72 76]
[200 242 288 338 392 450 512 578 648 722]


In [27]:
a=np.array([100,39,89,32,64,82,83,23])
a>40
a[a>40]

array([100,  89,  64,  82,  83])